# -*- coding: utf-8 -*-
"""music_genre_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UZzpe1VmhnAffP-_uLIz0DqwkL8q6Jor

# Music Genre Classification with Machine Learning

[Michelle Angelina](https://www.linkedin.com/in/mchelleangelina/)

## Libraries Import
"""

# Import Library
!pip install kaggle librosa tensorflow numpy matplotlib scikit-learn pydub > /dev/null 2>&1
!apt-get install ffmpeg -y > /dev/null 2>&1
!apt-get install sox -y > /dev/null 2>&1

import torchaudio
import json
from google.colab import files
import zipfile
import os
import librosa
import librosa.display
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split
import random
import pickle
from pydub import AudioSegment
from sklearn.preprocessing import StandardScaler, LabelEncoder
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.optimizers import AdamW
from tensorflow.keras.callbacks import ReduceLROnPlateau
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout, BatchNormalization, LSTM, Dense, Dropout
from tensorflow.keras.utils import to_categorical
import seaborn as sns
from sklearn.metrics import confusion_matrix, f1_score, classification_report

"""## Data Import"""

# Upload kaggle.json
files.upload()
!mkdir -p ~/.kaggle
!mv kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

"""Data used: https://www.kaggle.com/datasets/andradaolteanu/gtzan-dataset-music-genre-classification/data"""

# Download dataset
!kaggle datasets download -d andradaolteanu/gtzan-dataset-music-genre-classification

# Ekstrak dataset
with zipfile.ZipFile("gtzan-dataset-music-genre-classification.zip", 'r') as zip_ref:
    zip_ref.extractall("./data")

data_path = "./data/Data/genres_original"

error_files = []

for root, _, files in os.walk(data_path):
    for file in files:
        if file.endswith(".wav"):
            file_path = os.path.join(root, file)
            try:
                y, sr = librosa.load(file_path, sr=22050)
            except Exception as e:
                error_files.append((file_path, str(e)))

# Menampilkan file yang bermasalah
if error_files:
    print("File WAV yang error:")
    for f, err in error_files:
        print(f"{f} -> {err}")
else:
    print("Files are readable by librosa.")

genres = sorted(os.listdir(data_path))
print("Genres found:", genres)

total_files = sum([len(files) for _, _, files in os.walk(data_path)])
print(f"Total WAV files found: {total_files}")

"""## Data Preprocessing

### 1
"""

# Ekstraksi Fitur
def extract_features(y, sr, max_pad_len=40):
    # MFCC
    mfcc = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=40)

    # Chroma
    chroma = librosa.feature.chroma_stft(y=y, sr=sr)

    # Spectral Contrast
    spec_contrast = librosa.feature.spectral_contrast(y=y, sr=sr)

    # Zero-Crossing Rate
    zcr = librosa.feature.zero_crossing_rate(y)

    features = np.vstack([mfcc, chroma, spec_contrast, zcr])

    # Padding
    pad_width = max_pad_len - features.shape[1]
    if pad_width > 0:
        features = np.pad(features, pad_width=((0, 0), (0, pad_width)), mode='constant')
    else:
        features = features[:, :max_pad_len]

    return features

# Audio Augmentation
def augment_audio(y, sr):
    augmented_data = []

    # Add Noise
    noise = 0.005 * np.random.randn(len(y))
    y_noisy = y + noise
    augmented_data.append(y_noisy)

    # Pitch shifting
    n_steps = np.random.randint(-2, 3)
    if n_steps != 0:
        y_pitch = librosa.effects.pitch_shift(y=y, sr=sr, n_steps=n_steps)
        augmented_data.append(y_pitch)

    # Time stretching
    rate = np.random.uniform(0.8, 1.2)
    if rate != 1.0:
        y_stretch = librosa.effects.time_stretch(y, rate=rate)
        augmented_data.append(y_stretch)

    return augmented_data

X, y = [], []

genres = sorted(os.listdir(data_path))
genre_labels = {genre: idx for idx, genre in enumerate(genres)}

for genre in genres:
    genre_path = os.path.join(data_path, genre)
    if os.path.isdir(genre_path):
        for file in os.listdir(genre_path):
            if file.endswith(".wav"):
                file_path = os.path.join(genre_path, file)

                try:
                    y_raw, sr = librosa.load(file_path, sr=22050)

                    # Fitur asli
                    features = extract_features(y_raw, sr)
                    X.append(features)
                    y.append(genre_labels[genre])

                    # Augmentasi
                    augmented_audios = augment_audio(y_raw, sr)
                    for audio in augmented_audios:
                        features_aug = extract_features(audio, sr)
                        X.append(features_aug)
                        y.append(genre_labels[genre])
                except Exception as e:
                    print(f"Error processing {file_path}: {e}")

X = np.array(X)
y = np.array(y)

print(f"Dataset preprocessed. Shape: X={X.shape}, y={y.shape}")
print(f"Unique classes: {np.unique(y)}")

np.save("X_features.npy", X)
np.save("y_labels.npy", y)

with open("dataset.pkl", "wb") as f:
    pickle.dump((X, y), f)

# Load dataset
with open("dataset.pkl", "rb") as f:
    X, y = pickle.load(f)

print(f"Loaded dataset: X={X.shape}, y={y.shape}")

# Reshape untuk Standarisasi
X = X.reshape(X.shape[0], -1)

# Standarisasi
scaler = StandardScaler()
X = scaler.fit_transform(X)

X = X.reshape(X.shape[0], 40, -1)

num_classes = len(np.unique(y))
y = to_categorical(y, num_classes=num_classes)

"""## Model Training"""

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print(f"Final X_train shape: {X_train.shape}, y_train shape: {y_train.shape}")
print(f"Final X_test shape: {X_test.shape}, y_test shape: {y_test.shape}")

np.save("X_train.npy", X_train)
np.save("X_test.npy", X_test)
np.save("y_train.npy", y_train)
np.save("y_test.npy", y_test)

print("Preprocessing and splitting finished. Proceed to Model Training.")

# Arsitektur Model
model = Sequential([
    Conv1D(64, kernel_size=3, activation='relu', input_shape=(40, X_train.shape[2])),
    BatchNormalization(),
    MaxPooling1D(pool_size=2),

    Conv1D(128, kernel_size=3, activation='relu'),
    BatchNormalization(),
    MaxPooling1D(pool_size=2),

    LSTM(128, return_sequences=True),
    LSTM(64),

    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.3),
    Dense(num_classes, activation='softmax')
])

# Compile Model
model.compile(optimizer=AdamW(learning_rate=0.001), loss='categorical_crossentropy', metrics=['accuracy'])

# Callback
lr_reduction = ReduceLROnPlateau(monitor='val_loss', patience=3, factor=0.5, min_lr=1e-6, verbose=1)

# Training Model
history = model.fit(
    X_train, y_train,
    epochs=50,
    validation_split=0.2,
    batch_size=32,
    callbacks=[lr_reduction]
)

# Evaluasi Training
train_loss, train_acc = model.evaluate(X_train, y_train)
print(f"Train Accuracy: {train_acc * 100:.2f}%")

# Evaluasi Testing
test_loss, test_acc = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {test_acc * 100:.2f}%")

fig, ax = plt.subplots(1, 2, figsize=(12, 5))

# Plot Akurasi
ax[0].plot(history.history['accuracy'], label='Train Accuracy')
ax[0].plot(history.history['val_accuracy'], label='Validation Accuracy')
ax[0].set_xlabel('Epoch')
ax[0].set_ylabel('Accuracy')
ax[0].set_title('Model Accuracy')
ax[0].legend()

# Plot Loss
ax[1].plot(history.history['loss'], label='Train Loss')
ax[1].plot(history.history['val_loss'], label='Validation Loss')
ax[1].set_xlabel('Epoch')
ax[1].set_ylabel('Loss')
ax[1].set_title('Model Loss')
ax[1].legend()

plt.tight_layout()
plt.show()

y_test_labels = np.argmax(y_test, axis=1)

Y_pred = model.predict(X_test)
Y_pred_classes = np.argmax(Y_pred, axis=1)

f1 = f1_score(y_test_labels, Y_pred_classes, average='macro')
print(f'F1 Score (Macro): {f1:.4f}')

conf_matrix = confusion_matrix(y_test_labels, Y_pred_classes)

plt.figure(figsize=(8, 6))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues',
            xticklabels=sorted(genre_labels.keys()),
            yticklabels=sorted(genre_labels.keys()))

plt.title('Confusion Matrix Heatmap')
plt.xlabel('Predicted Labels')
plt.ylabel('True Labels')
plt.show()

Y_true_labels = np.argmax(y_test, axis=1)
print(classification_report(Y_true_labels, Y_pred_classes, target_names=sorted(genre_labels.keys())))

"""## Model Created"""

# Simpan Model
model.save("music_genre_classifier.h5")
print("music_genre_classifier.h5 has been saved.")

!pip freeze > requirements.txt
!cat requirements.txt

# Load
model = load_model("music_genre_classifier.h5")
model.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"])
X = np.load("X_features.npy")
y = np.load("y_labels.npy")

scaler = StandardScaler()
X = X.reshape(X.shape[0], -1)
X = scaler.fit_transform(X)

# Load genre
genres = sorted(os.listdir(data_path))

def extract_features_from_audio(file_path, max_pad_len=40):
    """Ekstraksi fitur dari file audio untuk prediksi"""
    y, sr = librosa.load(file_path, sr=22050)

    # Ekstraksi
    mfcc = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=40)
    chroma = librosa.feature.chroma_stft(y=y, sr=sr)
    spec_contrast = librosa.feature.spectral_contrast(y=y, sr=sr)
    zcr = librosa.feature.zero_crossing_rate(y)

    features = np.vstack([mfcc, chroma, spec_contrast, zcr])

    # Padding
    pad_width = max_pad_len - features.shape[1]
    if pad_width > 0:
        features = np.pad(features, pad_width=((0, 0), (0, pad_width)), mode='constant')
    else:
        features = features[:, :max_pad_len]

    return features

def predict_genre(file_path):
    """Fungsi untuk melakukan prediksi genre dari file audio"""
    feature = extract_features_from_audio(file_path)

    # Sesuaikan dimensi untuk model
    feature = feature.reshape(1, feature.shape[0], feature.shape[1])

    # Standarisasi fitur dengan scaler yang sudah dilatih
    feature = scaler.transform(feature.reshape(1, -1)).reshape(1, 40, -1)

    # Prediksi genre
    prediction = model.predict(feature)
    predicted_label = np.argmax(prediction)

    print(f"Predicted Genre: {genres[predicted_label]}")

# Contoh penggunaan: prediksi satu file random
random_file = random.choice(os.listdir("./data/Data/genres_original/classical"))
random_file_path = os.path.join("./data/Data/genres_original/classical", random_file)
predict_genre(random_file_path)